const { NotificationSink } = require('../../core/interfaces/NotificationSink');

class SlackNotificationSink extends NotificationSink {
  constructor(client) {
    super();
    this._client = client;
  }

  /**
   * @param {object} opts
   * @param {string} opts.header        Title shown in the message
   * @param {string} opts.summary       Markdown summary from the LLM
   * @param {string} [opts.transcript]  Full transcript text (uploaded as file)
   * @param {object} opts.context
   * @param {string} opts.context.outputChannel   Slack channel ID to post into
   * @param {number} [opts.context.messageCount]  Number of messages summarized
   * @param {string} [opts.context.periodDescription]  Human-readable time range
   */
  async post({ header, summary, transcript, context }) {
    const { outputChannel, channelId, messageCount, periodDescription } = context;

    const blocks = buildBlocks({ header, summary, channelId, messageCount, periodDescription });

    await this._client.chat.postMessage({
      channel: outputChannel,
      text: header, // plain-text fallback for push notifications / screen readers
      blocks,
    });

    if (transcript) {
      await this._client.filesUploadV2({
        channel_id: outputChannel,
        filename: 'transcript.txt',
        content: transcript,
        title: `Full transcript — ${header}`.slice(0, 255),
      });
    }
  }
}

function buildBlocks({ header, summary, channelId, messageCount, periodDescription }) {
  const blocks = [];

  // Slack header block only accepts plain_text — no mentions, no markdown
  blocks.push({
    type: 'section',
    text: { type: 'mrkdwn', text: header.slice(0, 150) },
  });

  // Channel tag must be in a mrkdwn section — it cannot go in the header block
  // if (channelId) {
  //   blocks.push({
  //     type: 'section',
  //     text: { type: 'mrkdwn', text: `<#${channelId}>` },
  //   });
  // }

  // Meta line: period + message count
  const metaParts = [];
  if (periodDescription) metaParts.push(periodDescription);
  if (messageCount != null) metaParts.push(`${messageCount} message${messageCount !== 1 ? 's' : ''}`);
  if (metaParts.length > 0) {
    blocks.push({
      type: 'context',
      elements: [{ type: 'mrkdwn', text: metaParts.join(' · ') }],
    });
  }

  blocks.push({ type: 'divider' });

  // Convert LLM Markdown to Slack mrkdwn before chunking
  const mrkdwn = toMrkdwn(summary);

  // Split into sections (Slack section blocks cap at 3000 chars)
  const sections = chunkText(mrkdwn, 2900);
  for (const chunk of sections) {
    blocks.push({
      type: 'section',
      text: { type: 'mrkdwn', text: chunk },
    });
  }

  blocks.push({ type: 'divider' });

  blocks.push({
    type: 'context',
    elements: [{ type: 'mrkdwn', text: '_Generated by Nexus AI bot_' }],
  });

  return blocks;
}

// Convert standard Markdown from the LLM into Slack mrkdwn.
// Slack mrkdwn differences: *bold* not **bold**, _italic_ not _italic_ (same),
// no # headings (use *bold* instead), no ~~strikethrough~~.
function toMrkdwn(text) {
  return text
    // ## Heading / ### Heading → *Heading*
    .replace(/^#{1,6}\s+(.+)$/gm, '*$1*')
    // **bold** → *bold*
    .replace(/\*\*(.+?)\*\*/g, '*$1*')
    // Strip bare horizontal rules (---, ***)
    .replace(/^[-*]{3,}\s*$/gm, '')
    // Collapse 3+ blank lines down to 2
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function chunkText(text, maxLen) {
  if (text.length <= maxLen) return [text];
  const chunks = [];
  let remaining = text;
  while (remaining.length > 0) {
    if (remaining.length <= maxLen) {
      chunks.push(remaining);
      break;
    }
    // Break at last newline before the limit so we don't cut mid-line
    let cut = remaining.lastIndexOf('\n', maxLen);
    if (cut === -1) cut = maxLen;
    chunks.push(remaining.slice(0, cut));
    remaining = remaining.slice(cut).trimStart();
  }
  return chunks;
}

module.exports = { SlackNotificationSink };
